name: granth_flutter
description: Aulieata Library - Digital Library Application
version: 4.8.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^7.0.7
  url_launcher: ^6.3.1
  html: ^0.15.5
  http: ^1.2.2
  intl: ^0.19.0
  share_plus: ^10.1.1
  package_info_plus: ^8.1.0

  # Animated Text
  animated_text_kit: ^4.2.2

  # Firebase
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5

  # STATE MANAGEMENT
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1

  # IMAGES
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # UI
  google_fonts: ^6.2.1

  #Push Notification
  onesignal_flutter: ^5.2.7

  #VOICE SEARCH
  speech_to_text: ^7.0.0

  # DOWNLOAD
  internet_file: ^1.2.0
  path_provider: ^2.1.5
  universal_html: ^2.2.4

  # PDF File
  flutter_pdfview: ^1.3.4

  # EPUB File
  flutter_epub_viewer: ^1.1.5
  # DATABASE
  sqflite: ^2.4.1

  #payment
  razorpay_flutter: ^1.3.7
  flutter_stripe: ^10.1.1

  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main

  paytm:
    git:
      url: https://github.com/iqonic-design/Paytm-All-in-one-flutter-sdk-master.git
      ref: 1.0.0

  #Google ads
  google_mobile_ads: ^5.2.0

  #Animation
  lottie: ^3.1.3

  #permission
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1

  flutter_downloader: ^1.11.8

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2
  flutter_launcher_icons: ^0.13.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs
dependency_overrides:
  http: ^0.13.4

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/app_icons/
    - images/app_images/
    - images/flag/
    - images/lottie/

# Add the flutter_launcher_icons configuration here
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/app_images/app_icon_padded.png"
  adaptive_icon_foreground: "images/app_images/app_icon_padded.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/app_images/app_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "images/app_images/app_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/app_images/app_logo.png"
